version: '3.5'

services:
  postgres:
    container_name: postgres_pinkgreen_mkt
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pinkgreen_mkt
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - MAX_CONNECTIONS=300
  rabbitmq:
    image: rabbitmq:3.6.9-management
    container_name: rabbitmq_pinkgreen_mkt
    ports:
      - 5672:5672
      - 15672:15672
  keycloak:
    container_name: keycloak_pinkgreen_mkt
    image: quay.io/keycloak/keycloak:13.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8180:8080