version: '3.5'

networks:
  pinkgreen-network:

services:
  postgres:
    container_name: postgres_pinkgreen_mkt
    image: postgres:13.2
    volumes:
      - ./psql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      MAX_CONNECTIONS: 300
    networks:
      - pinkgreen-network
  rabbitmq:
    image: rabbitmq:3.6.9-management
    container_name: rabbitmq_pinkgreen_mkt
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - pinkgreen-network
  keycloak:
    image: quay.io/keycloak/keycloak:13.0.0
    container_name: keycloak_pinkgreen_mkt
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: local
      DB_SCHEMA: public
      DB_PASSWORD: local
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    networks:
      - pinkgreen-network
    depends_on:
      - postgres