spring:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pinkgreen_mkt
    username: local
    password: local
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        bindings:
          process-order-payment-output:
            producer.routing-key-expression: '"process-order-payment"'
          process-order-payment-input:
            consumer.bindingRoutingKey: process-order-payment
      bindings:
        process-order-payment-output:
          destination: order_events
        process-order-payment-input:
          destination: order_events
          group: process-order-payment.pinkgreen

keycloak:
  realm: Pinkgreen-mkt
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: pinkgreen-backend
  credentials.secret: e0f06a0c-ce45-44d4-ac54-78395b715ffb
  use-resource-role-mappings: true
  bearer-only: true