spring:
  security.oauth2.resourceserver.jwt:
    issuer-uri: http://localhost:8080/realms/pinkgreen-mkt
    jwk-set-uri: http://localhost:8080/realms/pinkgreen-mkt/protocol/openid-connect/certs

  jpa.show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/pinkgreen_mkt
    user: local
    password: local
  datasource:
    url: jdbc:postgresql://localhost:5432/pinkgreen_mkt
    username: local
    password: local
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

payment.url: http://localhost:4000

iam.url: http://localhost:8080/admin/realms/pinkgreen-mkt