spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/pinkgreen_mkt
    username: local
    password: local
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5