spring:
  jpa.show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/pinkgreen_mkt
    user: local
    password: local
  datasource:
    url: jdbc:postgresql://localhost:5432/pinkgreen_mkt
    username: local
    password: local
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

keycloak:
  realm: Pinkgreen-mkt
  auth-server-url: http://localhost:8080/auth
  resource: pinkgreen-backend
  credentials.secret: cb6f474d-5a8a-44f7-b659-34e0fa8f95a0

payment:
  url: http://localhost:4000