spring:
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pinkgreen_mkt
    username: local
    password: local
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

keycloak:
  realm: Pinkgreen-mkt
  auth-server-url: http://localhost:8080/auth
  resource: pinkgreen-backend