server:
  port: 8181

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  cloud:
    function.definition: processOrderPaymentSupplier;processOrderPaymentConsumer
    stream:
      rabbit.bindings:
        processOrderPaymentSupplier-out-0:
          producer.routing-key-expression: '"process-order-payment"'
        processOrderPaymentConsumer-in-0:
          consumer.bindingRoutingKey: process-order-payment
      bindings:
        processOrderPaymentSupplier-out-0:
          destination: order_events
          binder: rabbit
          contentType: application/json
        processOrderPaymentConsumer-in-0:
          destination: order_events
          binder: rabbit
          contentType: application/json
          group: process-order-payment.pinkgreen

keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_URL}
  resource: ${KEYCLOAK_CLIENT}
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true