create TABLE PRODUCT_BRAND
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    BRAND_IMAGE VARCHAR(255)
);
create unique index PRODUCT_BRAND_NAME_IDX on PRODUCT_BRAND (NAME);

create TABLE PRODUCT
(
    ID               SERIAL PRIMARY KEY,
    ACTIVE           BOOLEAN,
    MAIN_IMAGE_URL   VARCHAR(255),
    NAME             VARCHAR(255),
    PRICE            DOUBLE PRECISION,
    PRODUCT_BRAND_ID INTEGER,
    FOREIGN KEY (PRODUCT_BRAND_ID) REFERENCES PRODUCT_BRAND (ID) ON DELETE CASCADE
);

create TABLE PRODUCT_CATEGORY
(
    ID    SERIAL PRIMARY KEY,
    IMAGE VARCHAR(255),
    NAME  VARCHAR(255)
);
create unique index PRODUCT_CATEGORY_NAME_IDX on PRODUCT_CATEGORY (NAME);

create TABLE PRODUCT_CATEGORIES
(
    PRODUCT_ID  INTEGER NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES product (ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES product_category (ID) ON DELETE CASCADE
);

create TABLE PRODUCT_SKU
(
    ID             SERIAL PRIMARY KEY,
    HEIGHT         DOUBLE PRECISION,
    LENGTH         DOUBLE PRECISION,
    ACTIVE         BOOLEAN,
    MAIN_IMAGE_URL VARCHAR(255),
    NAME           VARCHAR(255),
    PRICE          jsonb,
    SKU_ATTRIBUTES jsonb,
    SKU_CODE       VARCHAR(255),
    STOCK_QUANTITY INTEGER,
    URL_IMAGES     jsonb,
    WEIGHT         DOUBLE PRECISION,
    WIDTH          DOUBLE PRECISION,
    INDEX          INTEGER,
    PRODUCT_ID     INTEGER,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON DELETE CASCADE
);
create unique index PRODUCT_SKU_CODE_IDX on PRODUCT_SKU (SKU_CODE);
