create TABLE FAVORITE_PRODUCTS
(
    ID         SERIAL,
    USER_ID    VARCHAR(50)  NOT NULL,
    SKU_CODE   VARCHAR(255) NOT NULL,
    FOREIGN KEY (SKU_CODE) REFERENCES PRODUCT_SKU (SKU_CODE),
    PRIMARY KEY (ID, USER_ID, SKU_CODE)
);

