CREATE TABLE CUSTOMER_CATEGORY_INTENTIONS
(
    ID                  SERIAL          PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(255)    NOT NULL,
    CATEGORY_ID         INTEGER         NOT NULL,
    COUNTER             INTEGER         DEFAULT 1,
    FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX on CUSTOMER_CATEGORY_INTENTIONS (CUSTOMER_ID, CATEGORY_ID);
